/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as RemindersIndexRouteImport } from './routes/reminders.index'
import { Route as TaskTaskIdIndexRouteImport } from './routes/task.$taskId.index'
import { Route as TaskTaskIdStatusRouteImport } from './routes/task.$taskId.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersIndexRoute = RemindersIndexRouteImport.update({
  id: '/reminders/',
  path: '/reminders/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskTaskIdIndexRoute = TaskTaskIdIndexRouteImport.update({
  id: '/task/$taskId/',
  path: '/task/$taskId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskTaskIdStatusRoute = TaskTaskIdStatusRouteImport.update({
  id: '/task/$taskId/status',
  path: '/task/$taskId/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/payments': typeof PaymentsRoute
  '/reminders/': typeof RemindersIndexRoute
  '/task/$taskId/status': typeof TaskTaskIdStatusRoute
  '/task/$taskId/': typeof TaskTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/payments': typeof PaymentsRoute
  '/reminders': typeof RemindersIndexRoute
  '/task/$taskId/status': typeof TaskTaskIdStatusRoute
  '/task/$taskId': typeof TaskTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/payments': typeof PaymentsRoute
  '/reminders/': typeof RemindersIndexRoute
  '/task/$taskId/status': typeof TaskTaskIdStatusRoute
  '/task/$taskId/': typeof TaskTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/payments'
    | '/reminders/'
    | '/task/$taskId/status'
    | '/task/$taskId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/payments'
    | '/reminders'
    | '/task/$taskId/status'
    | '/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/payments'
    | '/reminders/'
    | '/task/$taskId/status'
    | '/task/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  PaymentsRoute: typeof PaymentsRoute
  RemindersIndexRoute: typeof RemindersIndexRoute
  TaskTaskIdStatusRoute: typeof TaskTaskIdStatusRoute
  TaskTaskIdIndexRoute: typeof TaskTaskIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/': {
      id: '/reminders/'
      path: '/reminders'
      fullPath: '/reminders/'
      preLoaderRoute: typeof RemindersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$taskId/': {
      id: '/task/$taskId/'
      path: '/task/$taskId'
      fullPath: '/task/$taskId/'
      preLoaderRoute: typeof TaskTaskIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$taskId/status': {
      id: '/task/$taskId/status'
      path: '/task/$taskId/status'
      fullPath: '/task/$taskId/status'
      preLoaderRoute: typeof TaskTaskIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  PaymentsRoute: PaymentsRoute,
  RemindersIndexRoute: RemindersIndexRoute,
  TaskTaskIdStatusRoute: TaskTaskIdStatusRoute,
  TaskTaskIdIndexRoute: TaskTaskIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
